[package]
name = "exercise_01"
version = "0.1.0"
edition = "2021"

[lib]
name = "exercise_01"
crate-type = ["cdylib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.17.5"
